apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - es-pvolume.yaml
  - es-service.yaml
  - es-statefulset.yaml
  - fluent-bit-clusterrole.yaml
  - fluent-bit-clusterrolebinding.yaml
  - fluent-bit-configmap.yaml
  - fluent-bit-sa.yaml
  - fluent-bit.yaml
  - kibana.yaml
 
